import 'app_locale.dart';

/// Lightweight hand-rolled localization (no codegen) so the UI can ship in
/// Uzbek, Russian and English from day one, per the project brief's
/// "local languages" requirement. Falls back to the Uzbek string if a key
/// is missing in the active locale.
class AppStrings {
  AppStrings._();

  static String t(AppLocale locale, String key) {
    final map = _strings[locale] ?? _strings[AppLocale.uz]!;
    return map[key] ?? _strings[AppLocale.uz]![key] ?? key;
  }

  static final Map<AppLocale, Map<String, String>> _strings = {
    AppLocale.uz: {
      'app_name': 'Vakil AI',
      'tagline': 'Sizning professional yuridik yordamchingiz',
      'get_started': 'Boshlash',
      'next': 'Keyingi',
      'skip': "O'tkazib yuborish",
      'back': 'Orqaga',
      'see_all': "Barchasi",
      'search': 'Qidirish',

      'onboarding_title_1': 'Xavflarni oldindan aniqlang',
      'onboarding_desc_1':
          "Sun'iy intellekt shartnomangizdagi xavfli va noqulay bandlarni avtomatik topib beradi",
      'onboarding_title_2': 'Hujjatlarni oson tushuning',
      'onboarding_desc_2':
          "Murakkab yuridik matnlar oddiy, tushunarli tilga o'giriladi",

      'welcome_headline': 'Welcome to\nVakil AI',
      'login_with_telegram': 'Telegram orqali kirish',
      'login_with_phone': 'Telefon raqam orqali',
      'agree_terms': 'Kirish orqali siz bizning Shartlar va Maxfiylik siyosatiga rozilik bildirasiz',
      'forgot_password': 'Parolni unutdingizmi?',

      'create_account_title': 'Hisobingizni yarating',
      'create_account_subtitle': "Xavfsiz, sun'iy intellekt asosidagi yuridik tahlil",
      'phone_or_email': 'Telefon raqam yoki Email',
      'password': 'Parol',
      'register': "Ro'yxatdan o'tish",
      'already_have_account': 'Hisobingiz bormi?',
      'no_account': 'Hisobingiz yo\'qmi?',
      'log_in': 'Kirish',
      'or_continue_with': 'yoki davom eting',
      'secured_by': 'Vakil AI shifrlash bilan himoyalangan',

      'recent_documents': 'So\'nggi hujjatlar',
      'telegram_synced': 'Telegram sinxronlandi',
      'scan': 'Skanerlash',
      'voice_mode': 'Ovozli rejim',
      'nav_home': 'Bosh sahifa',
      'nav_history': 'Tarix',
      'nav_scan': 'Skaner',
      'nav_chat': 'Chat',
      'nav_profile': 'Profil',

      'risk_high': 'Yuqori xavf',
      'risk_medium': "O'rta xavf",
      'risk_low': 'Past xavf',
      'risk_clear': 'Toza',

      'document_scanner': 'Hujjat skaneri',
      'clause_identified': 'Band aniqlandi',
      'point_camera_hint': 'Hujjatni kadrga to\'liq joylashtiring',
      'gallery': 'Galereya',

      'analysis_detail': 'Tahlil tafsilotlari',
      'original_text': 'Hujjat matni',
      'plain_summary': 'Sodda tildagi xulosa',
      'compliance_score': 'Muvofiqlik darajasi',
      'download_pdf': 'PDF yuklab olish',
      'share_telegram': "Telegram'da ulashish",
      'powered_by': 'Google Gemini asosida ishlaydi',
      'key_obligations': 'Asosiy majburiyatlar',
      'key_dates': 'Muhim sanalar',

      'ai_advisor': 'AI Yordamchi',
      'type_question': 'Yuridik savolingizni yozing...',
      'attach_document': 'Hujjat biriktirish',
      'grounded_notice': 'Javoblar faqat yuklangan hujjatga asoslanadi',

      'search_history': 'Tarixdan qidirish',
      'filter': 'Filtr',
      'add_new_document': 'Yangi hujjat qo\'shish',
      'risk_score': 'Xavf darajasi',

      'settings': 'Sozlamalar',
      'interface_language': 'Interfeys tili',
      'auto_translate': 'Avtomatik tarjima',
      'risk_notifications': 'Xavf bildirishnomalari',
      'language_detection': 'Tilni aniqlash',
      'account_settings': 'Hisob sozlamalari',
      'privacy': 'Maxfiylik',
      'help': 'Yordam',
      'logout': 'Chiqish',
      'telegram_bot_integration': 'Telegram Bot integratsiyasi',
      'connected': 'Ulangan',
      'not_connected': 'Ulanmagan',
      'notifications': 'Bildirishnomalar',
      'instant_notifications': 'Tezkor bildirishnomalar',
      'cloud_archive': 'Bulutli arxiv',
      'sync_options': 'Sinxronizatsiya',
      'sync_history': 'Tarixni sinxronlash',
      'sync_documents': 'Hujjatlarni sinxronlash',
      'unlink_telegram': 'Telegram hisobini uzish',

      'free_tier_badge': 'Bepul: 2/2 hujjat qoldi',
      'upgrade_premium': 'Premiumga o\'tish',
      'compliance_gdpr': 'GDPR',
      'compliance_ccpa': 'CCPA',
      'compliance_hipaa': 'HIPAA',
    },
    AppLocale.ru: {
      'app_name': 'Vakil AI',
      'tagline': 'Ваш профессиональный юридический помощник',
      'get_started': 'Начать',
      'next': 'Далее',
      'skip': 'Пропустить',
      'back': 'Назад',
      'see_all': 'Все',
      'search': 'Поиск',

      'onboarding_title_1': 'Выявляйте риски заранее',
      'onboarding_desc_1':
          'ИИ автоматически находит рискованные и невыгодные пункты в вашем договоре',
      'onboarding_title_2': 'Понимайте документы легко',
      'onboarding_desc_2': 'Сложный юридический текст переводится на простой язык',

      'welcome_headline': 'Добро пожаловать\nв Vakil AI',
      'login_with_telegram': 'Войти через Telegram',
      'login_with_phone': 'По номеру телефона',
      'agree_terms': 'Входя в систему, вы соглашаетесь с Условиями и Политикой конфиденциальности',
      'forgot_password': 'Забыли пароль?',

      'create_account_title': 'Создайте аккаунт',
      'create_account_subtitle': 'Безопасный юридический анализ на основе ИИ',
      'phone_or_email': 'Телефон или Email',
      'password': 'Пароль',
      'register': 'Зарегистрироваться',
      'already_have_account': 'Уже есть аккаунт?',
      'no_account': 'Нет аккаунта?',
      'log_in': 'Войти',
      'or_continue_with': 'или продолжите с',
      'secured_by': 'Защищено шифрованием Vakil AI',

      'recent_documents': 'Недавние документы',
      'telegram_synced': 'Telegram синхронизирован',
      'scan': 'Сканировать',
      'voice_mode': 'Голосовой режим',
      'nav_home': 'Главная',
      'nav_history': 'История',
      'nav_scan': 'Скан',
      'nav_chat': 'Чат',
      'nav_profile': 'Профиль',

      'risk_high': 'Высокий риск',
      'risk_medium': 'Средний риск',
      'risk_low': 'Низкий риск',
      'risk_clear': 'Чисто',

      'document_scanner': 'Сканер документов',
      'clause_identified': 'Пункт определён',
      'point_camera_hint': 'Расположите документ полностью в кадре',
      'gallery': 'Галерея',

      'analysis_detail': 'Детали анализа',
      'original_text': 'Текст документа',
      'plain_summary': 'Краткое изложение',
      'compliance_score': 'Уровень соответствия',
      'download_pdf': 'Скачать PDF',
      'share_telegram': 'Поделиться в Telegram',
      'powered_by': 'Работает на Google Gemini',
      'key_obligations': 'Основные обязательства',
      'key_dates': 'Важные даты',

      'ai_advisor': 'ИИ Советник',
      'type_question': 'Введите ваш юридический вопрос...',
      'attach_document': 'Прикрепить документ',
      'grounded_notice': 'Ответы основаны только на загруженном документе',

      'search_history': 'Поиск по истории',
      'filter': 'Фильтр',
      'add_new_document': 'Добавить документ',
      'risk_score': 'Оценка риска',

      'settings': 'Настройки',
      'interface_language': 'Язык интерфейса',
      'auto_translate': 'Автоперевод',
      'risk_notifications': 'Уведомления о рисках',
      'language_detection': 'Определение языка',
      'account_settings': 'Настройки аккаунта',
      'privacy': 'Конфиденциальность',
      'help': 'Помощь',
      'logout': 'Выйти',
      'telegram_bot_integration': 'Интеграция с Telegram Bot',
      'connected': 'Подключено',
      'not_connected': 'Не подключено',
      'notifications': 'Уведомления',
      'instant_notifications': 'Мгновенные уведомления',
      'cloud_archive': 'Облачный архив',
      'sync_options': 'Синхронизация',
      'sync_history': 'Синхронизировать историю',
      'sync_documents': 'Синхронизировать документы',
      'unlink_telegram': 'Отвязать Telegram',

      'free_tier_badge': 'Бесплатно: осталось 2/2',
      'upgrade_premium': 'Перейти на Премиум',
      'compliance_gdpr': 'GDPR',
      'compliance_ccpa': 'CCPA',
      'compliance_hipaa': 'HIPAA',
    },
    AppLocale.en: {
      'app_name': 'Vakil AI',
      'tagline': 'Your professional legal assistant',
      'get_started': 'Get Started',
      'next': 'Next',
      'skip': 'Skip',
      'back': 'Back',
      'see_all': 'See all',
      'search': 'Search',

      'onboarding_title_1': 'Spot risks before you sign',
      'onboarding_desc_1':
          'AI automatically flags risky and one-sided clauses in your contract',
      'onboarding_title_2': 'Understand documents easily',
      'onboarding_desc_2': 'Dense legal text, translated into plain language',

      'welcome_headline': 'Welcome to\nVakil AI',
      'login_with_telegram': 'Continue with Telegram',
      'login_with_phone': 'Continue with phone number',
      'agree_terms': 'By logging in, you agree to our Terms and Privacy Policy',
      'forgot_password': 'Forgot your password?',

      'create_account_title': 'Create Your Account',
      'create_account_subtitle': 'Secure AI-powered legal insight',
      'phone_or_email': 'Phone Number or Email',
      'password': 'Password',
      'register': 'Register',
      'already_have_account': 'Already have an account?',
      'no_account': 'Don\'t have an account?',
      'log_in': 'Log In',
      'or_continue_with': 'or continue with',
      'secured_by': 'Secured by Vakil AI Encryption',

      'recent_documents': 'Recent Documents',
      'telegram_synced': 'Telegram Synced',
      'scan': 'Scan',
      'voice_mode': 'Voice Mode',
      'nav_home': 'Home',
      'nav_history': 'History',
      'nav_scan': 'Scan',
      'nav_chat': 'Chat',
      'nav_profile': 'Profile',

      'risk_high': 'High Risk',
      'risk_medium': 'Medium Risk',
      'risk_low': 'Low Risk',
      'risk_clear': 'Clear',

      'document_scanner': 'Document Scanner',
      'clause_identified': 'Clause identified',
      'point_camera_hint': 'Fit the whole document in frame',
      'gallery': 'Gallery',

      'analysis_detail': 'Analysis Detail',
      'original_text': 'Original Document Text',
      'plain_summary': 'Plain-language Summary',
      'compliance_score': 'Compliance Score',
      'download_pdf': 'Download PDF',
      'share_telegram': 'Share to Telegram',
      'powered_by': 'Powered by Google Gemini',
      'key_obligations': 'Key Obligations',
      'key_dates': 'Key Dates',

      'ai_advisor': 'AI Advisor',
      'type_question': 'Type your legal question...',
      'attach_document': 'Attach Document',
      'grounded_notice': 'Answers are grounded strictly in your uploaded document',

      'search_history': 'Search History',
      'filter': 'Filter',
      'add_new_document': 'Add New Document',
      'risk_score': 'Risk Score',

      'settings': 'Settings',
      'interface_language': 'Interface Language',
      'auto_translate': 'Auto-Translate',
      'risk_notifications': 'Risk Notifications',
      'language_detection': 'Language Detection',
      'account_settings': 'Account Settings',
      'privacy': 'Privacy',
      'help': 'Help',
      'logout': 'Log Out',
      'telegram_bot_integration': 'Telegram Bot Integration',
      'connected': 'Connected',
      'not_connected': 'Not Connected',
      'notifications': 'Notifications',
      'instant_notifications': 'Instant Notifications',
      'cloud_archive': 'Cloud Archive',
      'sync_options': 'Sync Options',
      'sync_history': 'Sync History',
      'sync_documents': 'Sync Documents',
      'unlink_telegram': 'Unlink Telegram Account',

      'free_tier_badge': 'Free: 2/2 reviews left',
      'upgrade_premium': 'Upgrade to Premium',
      'compliance_gdpr': 'GDPR',
      'compliance_ccpa': 'CCPA',
      'compliance_hipaa': 'HIPAA',
    },
  };
}
